name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project
        run: |
          pip install .

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import importlib
          import sys
          # Avoid importing QtWebEngine view in headless run by not importing video_editor
          importlib.import_module('youtube_downloader')
          importlib.import_module('video_splitter')
          print('Imports OK')
          PY
